apiVersion: v1
kind: ConfigMap
metadata:
  name: icp-mysql-config-vol
  labels:
    app: my-mysql
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    # http://www.percona.com/blog/2008/05/31/dns-achilles-heel-mysql-installation/
    skip_name_resolve
    #server-id
    #log-bin
    
    # Optimize mysql configuration
    query_cache_size = 0
    # innodb_file_per_table
    innodb_buffer_pool_size = 128M
    innodb_flush_log_at_trx_commit = 1
    symbolic-links=0
    sql_mode=NO_ENGINE_SUBSTITUTION
    # STRICT_TRANS_TABLES
    performance_schema = off
    innodb_use_native_aio = 0
    lower_case_table_names=1
  mysqld_charset.cnf: |
    [mysqld]
    character_set_server=utf8
    character_set_filesystem=utf8
    collation-server=utf8_general_ci
    init-connect='SET NAMES utf8'
    init_connect='SET collation_connection = utf8_general_ci'

