apiVersion: v1
kind: Service
metadata:
  name: my-mysql
  labels:
    name: my-mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30011
  selector:
    name: my-mysql
