apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dubboadmin
  labels:
    app: dubboadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dubboadmin
    spec:
      containers:
      - name: duboadmin
        image: 3.3.3.122/test/dubboadmin:1.0
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harhor-m2-2
