apiVersion: v1
kind: Service
metadata:
  name: icp-service-flightz
  labels:
    name: icp-service-flightz
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: icp-service-flightz
  type: NodePort
