apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-web
provisioner: kubernetes.io/rbd
parameters:
  monitors: 3.3.3.119,3.3.3.123,3.3.3.124
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: galera
  pool: rbd 
  userId: admin
  userSecretName: ceph-secret
