apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: galera
  labels:
    app: mysql
data:
  # Root password: changeit run  echo -n heshengkai|base64
  root-password: aGVzaGVuZ2thaQ==
  # Root user: root
  root-user: cm9vdA==
