apiVersion: v1
kind: ReplicationController
metadata:
  name: zoo
  labels:
    name: zoo
spec:
  replicas: 1
  selector:
    name: zoo
  template:
    metadata:
      labels:
        name: zoo
    spec:
      containers:
      - name: zoo
        image: jplock/zookeeper:3.4.8 
        ports:
        - containerPort: 2181
  
